working on spotify genre dataset

In [8]:
import pandas as pd
import numpy as np

In [9]:
spotify_df = pd.read_csv(r'C:\Users\navan\Desktop\spotify\Spotify_2000.csv')

data src = https://www.kaggle.com/iamsumat/spotify-top-2000s-mega-dataset

In [10]:
spotify_df.head()

Index                   Title             Artist            Top Genre  \
0      1                 Sunrise        Norah Jones      adult standards   
1      2             Black Night        Deep Purple           album rock   
2      3          Clint Eastwood           Gorillaz  alternative hip hop   
3      4           The Pretender       Foo Fighters    alternative metal   
4      5  Waitin' On A Sunny Day  Bruce Springsteen         classic rock   

   Year  Beats Per Minute (BPM)  Energy  Danceability  Loudness (dB)  \
0  2004                     157      30            53            -14   
1  2000                     135      79            50            -11   
2  2001                     168      69            66             -9   
3  2007                     173      96            43             -4   
4  2002                     106      82            58             -5   

   Liveness  Valence Length (Duration)  Acousticness  Speechiness  Popularity  
0        11       68               201            94            3          71  
1        17       81               207            17            7          39  
2         7       52               341             2           17          69  
3         3       37               269             0            4          76  
4        10       87               256             1            3          59

In [11]:
for (i,j) in spotify_df.iterrows():
    spotify_df.loc[i,"Top Genre"]=spotify_df.loc[i,"Top Genre"].split()[-1]

In [12]:
spotify_df

Index                   Title                    Artist  Top Genre  \
0         1                 Sunrise               Norah Jones  standards   
1         2             Black Night               Deep Purple       rock   
2         3          Clint Eastwood                  Gorillaz        hop   
3         4           The Pretender              Foo Fighters      metal   
4         5  Waitin' On A Sunny Day         Bruce Springsteen       rock   
...     ...                     ...                       ...        ...   
1989   1990        Heartbreak Hotel             Elvis Presley  standards   
1990   1991               Hound Dog             Elvis Presley  standards   
1991   1992         Johnny B. Goode               Chuck Berry       rock   
1992   1993               Take Five  The Dave Brubeck Quartet      bebop   
1993   1994          Blueberry Hill               Fats Domino  standards   

      Year  Beats Per Minute (BPM)  Energy  Danceability  Loudness (dB)  \
0     2004                     157      30            53            -14   
1     2000                     135      79            50            -11   
2     2001                     168      69            66             -9   
3     2007                     173      96            43             -4   
4     2002                     106      82            58             -5   
...    ...                     ...     ...           ...            ...   
1989  1958                      94      21            70            -12   
1990  1958                     175      76            36             -8   
1991  1959                     168      80            53             -9   
1992  1959                     174      26            45            -13   
1993  1959                     133      50            49            -10   

      Liveness  Valence Length (Duration)  Acousticness  Speechiness  \
0           11       68               201            94            3   
1           17       81               207            17            7   
2            7       52               341             2           17   
3            3       37               269             0            4   
4           10       87               256             1            3   
...        ...      ...               ...           ...          ...   
1989        11       72               128            84            7   
1990        76       95               136            73            6   
1991        31       97               162            74            7   
1992         7       60               324            54            4   
1993        16       83               148            74            3   

      Popularity  
0             71  
1             39  
2             69  
3             76  
4             59  
...          ...  
1989          63  
1990          69  
1991          74  
1992          65  
1993          56  

[1994 rows x 15 columns]

In [13]:
spotify_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Index                   1994 non-null   int64 
 1   Title                   1994 non-null   object
 2   Artist                  1994 non-null   object
 3   Top Genre               1994 non-null   object
 4   Year                    1994 non-null   int64 
 5   Beats Per Minute (BPM)  1994 non-null   int64 
 6   Energy                  1994 non-null   int64 
 7   Danceability            1994 non-null   int64 
 8   Loudness (dB)           1994 non-null   int64 
 9   Liveness                1994 non-null   int64 
 10  Valence                 1994 non-null   int64 
 11  Length (Duration)       1994 non-null   object
 12  Acousticness            1994 non-null   int64 
 13  Speechiness             1994 non-null   int64 
 14  Popularity              1994 non-null   int64 
dtypes: i

In [105]:
df=spotify_df.groupby(['Top Genre'])["Top Genre"]
df2=pd.DataFrame(df.describe())
type(df2)

pandas.core.frame.DataFrame

In [106]:
df2

count unique          top freq
Top Genre                                 
afropop         1      1      afropop    1
alternative     1      1  alternative    1
ambient         1      1      ambient    1
americana      13      1    americana   13
anthem-folk     1      1  anthem-folk    1
...           ...    ...          ...  ...
soundtrack      1      1   soundtrack    1
standards     123      1    standards  123
streektaal      1      1   streektaal    1
trance          1      1       trance    1
wave           38      1         wave   38

[68 rows x 4 columns]

In [107]:
df2=df2.sort_values("count",ascending=False)

In [108]:
df2

count unique          top freq
Top Genre                                 
rock          856      1         rock  856
pop           333      1          pop  333
standards     123      1    standards  123
metal          93      1        metal   93
indie          77      1        indie   77
...           ...    ...          ...  ...
bebop           1      1        bebop    1
basshall        1      1     basshall    1
anthem-folk     1      1  anthem-folk    1
ambient         1      1      ambient    1
hardcore        1      1     hardcore    1

[68 rows x 4 columns]

In [109]:
df2 = df2[df2["count"]>90]
df2

count unique        top freq
Top Genre                             
rock        856      1       rock  856
pop         333      1        pop  333
standards   123      1  standards  123
metal        93      1      metal   93

In [110]:
genre_list=list(df2.index)
genre_list

['rock', 'pop', 'standards', 'metal']

In [111]:
cur_df = spotify_df[spotify_df["Top Genre"].isin(genre_list)]

In [112]:
cur_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1405 entries, 0 to 1993
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Index                   1405 non-null   int64 
 1   Title                   1405 non-null   object
 2   Artist                  1405 non-null   object
 3   Top Genre               1405 non-null   object
 4   Year                    1405 non-null   int64 
 5   Beats Per Minute (BPM)  1405 non-null   int64 
 6   Energy                  1405 non-null   int64 
 7   Danceability            1405 non-null   int64 
 8   Loudness (dB)           1405 non-null   int64 
 9   Liveness                1405 non-null   int64 
 10  Valence                 1405 non-null   int64 
 11  Length (Duration)       1405 non-null   object
 12  Acousticness            1405 non-null   int64 
 13  Speechiness             1405 non-null   int64 
 14  Popularity              1405 non-null   int64 
dtypes: i

In [113]:
features = ["Energy","Loudness (dB)","Acousticness","Valence","Beats Per Minute (BPM)",]

In [114]:
from sklearn.model_selection import train_test_split
X=cur_df[features]
y=cur_df["Top Genre"]

In [115]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [116]:
X_scaled

array([[0.27835052, 0.52      , 0.94949495, 0.67708333, 0.71005917],
       [0.78350515, 0.64      , 0.17171717, 0.8125    , 0.57988166],
       [0.95876289, 0.92      , 0.        , 0.35416667, 0.80473373],
       ...,
       [0.75257732, 0.76      , 0.73737374, 0.95833333, 0.81656805],
       [0.79381443, 0.72      , 0.74747475, 0.97916667, 0.77514793],
       [0.48453608, 0.68      , 0.74747475, 0.83333333, 0.56804734]])

In [117]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_encoded.reshape(y_encoded.shape[0])

array([3, 2, 0, ..., 3, 2, 3])

In [118]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y_encoded,test_size=0.1,random_state=0)

In [119]:
len(X_train)

1264

In [120]:
len(X_test)

141

In [121]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=10, random_state=0)
forest.fit(X_train, y_train)
forest.score(X_test, y_test)

0.5815602836879432

In [122]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
tree.score(X_test, y_test)

0.48226950354609927

In [123]:
from sklearn.svm import SVC
svm = SVC(kernel='rbf')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.6737588652482269

In [124]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

0.6808510638297872

In [125]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.5957446808510638

In [126]:
import xgboost

In [127]:
params={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

In [128]:
from sklearn.model_selection import RandomizedSearchCV

In [129]:
classifier=xgboost.XGBClassifier()


In [130]:
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='roc_auc',n_jobs=-1,cv=5,verbose=3)

In [131]:
score=classifier.fit(X_scaled,y_encoded)

C:\Users\navan\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[11:19:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [132]:
from sklearn.model_selection import cross_val_score
score =cross_val_score(classifier,X_scaled,y_encoded)

C:\Users\navan\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[11:19:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[11:19:43] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[11:19:44] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[11:19:44] WARNING: C:/Users/Administrator/workspace/xgboost-win64_

In [133]:
score

array([0.51957295, 0.56227758, 0.5658363 , 0.55160142, 0.53736655])

In [136]:
cross_val_score(KNeighborsClassifier(n_neighbors=5),X_scaled,y_encoded)

array([0.48754448, 0.51957295, 0.58718861, 0.55160142, 0.53380783])

In [135]:
cross_val_score(RandomForestClassifier(n_estimators=10, random_state=0),X_scaled,y_encoded)

array([0.44839858, 0.53380783, 0.54448399, 0.5480427 , 0.52669039])

In [137]:
cross_val_score(SVC(kernel='rbf'),X_scaled,y_encoded)

array([0.60854093, 0.60142349, 0.60854093, 0.61209964, 0.59430605])